// Code generated by "stringer -type=AtomType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Num-0]
	_ = x[Quot-1]
	_ = x[List-2]
	_ = x[Sym-3]
}

const _AtomType_name = "NumQuotListSym"

var _AtomType_index = [...]uint8{0, 3, 7, 11, 14}

func (i AtomType) String() string {
	if i >= AtomType(len(_AtomType_index)-1) {
		return "AtomType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AtomType_name[_AtomType_index[i]:_AtomType_index[i+1]]
}
